import { DEFAULT_API_URL } from '../config.js'

const DEFAULT_ROBOT = {
  name: 'My Robot',
  api_url: DEFAULT_API_URL,
  features: ['home', 'dome', 'body', 'audio', 'scripts', 'lights'],
}

export const BUILTIN_PROFILES = [
  {
    id: 'dark',
    label: 'Dark Mono',
    layout: 'sidebar',
    builtin: true,
    colors: {
      '--bg-primary':    '#0c0c0c',
      '--bg-secondary':  '#161616',
      '--bg-tertiary':   '#111111',
      '--bg-surface':    '#1e1e1e',
      '--bg-hover':      '#282828',
      '--border':        '#2a2a2a',
      '--border-strong': '#404040',
      '--accent':        '#ffffff',
      '--accent-dim':    'rgba(255, 255, 255, 0.06)',
      '--text-primary':  '#f0f0f0',
      '--text-secondary':'#666666',
      '--text-muted':    '#3a3a3a',
      '--success':       '#22c55e',
      '--danger':        '#ef4444',
      '--btn-primary':      '#2563eb',
      '--btn-primary-text': '#ffffff',
    },
    robot: { ...DEFAULT_ROBOT },
  },
  {
    id: 'light',
    label: 'Light Mono',
    layout: 'sidebar',
    builtin: true,
    colors: {
      '--bg-primary':    '#fafafa',
      '--bg-secondary':  '#f0f0f0',
      '--bg-tertiary':   '#f5f5f5',
      '--bg-surface':    '#e8e8e8',
      '--bg-hover':      '#dcdcdc',
      '--border':        '#d8d8d8',
      '--border-strong': '#b0b0b0',
      '--accent':        '#000000',
      '--accent-dim':    'rgba(0, 0, 0, 0.05)',
      '--text-primary':  '#0f0f0f',
      '--text-secondary':'#767676',
      '--text-muted':    '#c0c0c0',
      '--success':       '#16a34a',
      '--danger':        '#dc2626',
      '--btn-primary':      '#2563eb',
      '--btn-primary-text': '#ffffff',
    },
    robot: { ...DEFAULT_ROBOT },
  },
  {
    id: 'touch',
    label: 'Slate Touch',
    layout: 'touch',
    builtin: true,
    colors: {
      '--bg-primary':    '#0d1117',
      '--bg-secondary':  '#161c26',
      '--bg-tertiary':   '#111827',
      '--bg-surface':    '#1e2a3a',
      '--bg-hover':      '#253447',
      '--border':        '#2a3545',
      '--border-strong': '#3d4f63',
      '--accent':        '#58a6ff',
      '--accent-dim':    'rgba(88, 166, 255, 0.08)',
      '--text-primary':  '#e6edf3',
      '--text-secondary':'#7d8590',
      '--text-muted':    '#30363d',
      '--success':       '#3fb950',
      '--danger':        '#f85149',
    },
    robot: { ...DEFAULT_ROBOT },
  },
  {
    id: 'dark-touch',
    label: 'Dark Touch',
    layout: 'touch',
    builtin: true,
    colors: {
      '--bg-primary':    '#0c0c0c',
      '--bg-secondary':  '#161616',
      '--bg-tertiary':   '#111111',
      '--bg-surface':    '#1e1e1e',
      '--bg-hover':      '#282828',
      '--border':        '#2a2a2a',
      '--border-strong': '#404040',
      '--accent':        '#ffffff',
      '--accent-dim':    'rgba(255, 255, 255, 0.06)',
      '--text-primary':  '#f0f0f0',
      '--text-secondary':'#666666',
      '--text-muted':    '#3a3a3a',
      '--success':       '#22c55e',
      '--danger':        '#ef4444',
    },
    robot: { ...DEFAULT_ROBOT },
  },
  {
    id: 'light-touch',
    label: 'Light Touch',
    layout: 'touch',
    builtin: true,
    colors: {
      '--bg-primary':    '#fafafa',
      '--bg-secondary':  '#f0f0f0',
      '--bg-tertiary':   '#f5f5f5',
      '--bg-surface':    '#e8e8e8',
      '--bg-hover':      '#dcdcdc',
      '--border':        '#d8d8d8',
      '--border-strong': '#b0b0b0',
      '--accent':        '#000000',
      '--accent-dim':    'rgba(0, 0, 0, 0.05)',
      '--text-primary':  '#0f0f0f',
      '--text-secondary':'#767676',
      '--text-muted':    '#c0c0c0',
      '--success':       '#16a34a',
      '--danger':        '#dc2626',
      '--btn-primary':      '#2563eb',
      '--btn-primary-text': '#ffffff',
    },
    robot: { ...DEFAULT_ROBOT },
  },
]
